from . import loginController
from . import signUpController
from . import getClientsController
from . import logoutController
from . import searchClientController
from . import getClientProfilesController
from . import getClientGenInfoController
from . import getClientWorkoutGoalController
from . import getCoachesController
from . import signUpCoachController
from . import filterCoachesByStateController
from . import filterCoachesByTownController
from . import filterCoachesByGymController
from . import filterCoachesByGoalsController
from . import filterCoachesByCostController
from . import filterCoachesByExpController
from . import filterCoachesByIdController
from . import filterCoachesByRatingController

from . import searchCoachController
from . import doneSurveyController
from . import doneCoachSurveyController