from . import loginController
from . import signUpController
from . import getClientsController
from . import logoutController
from . import searchClientController
from . import getGenInfoController
from . import getClientGenInfoController
from . import getClientWorkoutGoalController
from . import getCoachesController